apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplenode_deploy
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: samplepod
          image: sampleone
          ports:
            - containerPort: 3000
