apiVersion: v1
kind: Service
metadata:
  name: your-service-name
  labels:
    app: your-app-label
spec:
  selector:
    app: your-app-label
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
